<a href="https://colab.research.google.com/github/Shaunlipy/Pytorch_operations/blob/main/Pytorch_Einsum_Einops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
print(torch.__version__)

1.8.1+cu101


In [ ]:
# 1
a = torch.rand(2, 3)
b = torch.rand(3, 4)
c = torch.einsum('ik,kj -> ij', [a, b])
d = torch.mm(a, b) # c equivalent to d
print(c)
print(d)

tensor([[0.6971, 0.7975, 0.5028, 0.4894],
        [0.5703, 0.5612, 0.1938, 0.4922]])
tensor([[0.6971, 0.7975, 0.5028, 0.4894],
        [0.5703, 0.5612, 0.1938, 0.4922]])


In [ ]:
# 2
a = torch.randn(2, 3, 5, 7, 9)
# i = 7, j = 9
b = torch.einsum('...ij -> ...ji', [a])
c = a.permute(0, 1, 2, 4, 3)
print(b.shape)
print(c.shape)

torch.Size([2, 3, 5, 9, 7])
torch.Size([2, 3, 5, 9, 7])


In [ ]:
# 3
a = torch.arange(9).reshape(3, 3)

b = torch.einsum('ii -> i', [a])
c = torch.diagonal(a, 0)

print(b)
print(c)

tensor([0, 4, 8])
tensor([0, 4, 8])


In [ ]:
# 4
a = torch.arange(6).reshape(2, 3)

b = torch.einsum('ij -> ji', [a])
c = torch.transpose(a, 0, 1)

print(b)
print(c)

tensor([[0, 3],
        [1, 4],
        [2, 5]])
tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [ ]:
# 5 
a = torch.arange(6).reshape(2, 3)

b = torch.einsum('ij ->', [a])
c = torch.sum(a)

print(b)
print(c)

tensor(15)
tensor(15)


In [ ]:
# 6
a = torch.arange(6).reshape(2, 3)

b = torch.einsum('ij ->j', [a])
c = torch.sum(a, dim=0)

print(b)
print(c)

tensor([3, 5, 7])
tensor([3, 5, 7])


In [ ]:
# 7
a = torch.arange(6).reshape(2, 3)
b = torch.arange(3)

c = torch.einsum('ik,k -> i', [a, b])
d = torch.mv(a, b)
e = torch.einsum('ik,k', [a, b])

print(c)
print(d)
print(e)

tensor([ 5, 14])
tensor([ 5, 14])
tensor([ 5, 14])


In [ ]:
# 8 
a = torch.arange(6).reshape(2, 3)
b = torch.arange(15).reshape(3, 5)

c = torch.einsum('ik,kj->ij', [a, b])
d = torch.mm(a,b)
e = torch.einsum('ik,kj', [a, b])

print(c)
print(d)
print(e)

tensor([[ 25,  28,  31,  34,  37],
        [ 70,  82,  94, 106, 118]])
tensor([[ 25,  28,  31,  34,  37],
        [ 70,  82,  94, 106, 118]])
tensor([[ 25,  28,  31,  34,  37],
        [ 70,  82,  94, 106, 118]])


In [ ]:
# 9
a = torch.arange(3)
b = torch.arange(3, 6)

c = torch.einsum('i,i ->', [a, b])
d = torch.einsum('i,i', [a, b])
e = torch.dot(a, b)

print(c)
print(d)
print(e)

tensor(14)
tensor(14)
tensor(14)


In [ ]:
# 10
a = torch.arange(6).reshape(2, 3)
b = torch.arange(6, 12).reshape(2, 3)

c = torch.einsum('ij,ij->', [a,b])
d = torch.einsum('ij, ij', [a, b])
e = (a * b).sum()

print(c)
print(d)
print(e)

tensor(145)
tensor(145)
tensor(145)


In [ ]:
# 11
a = torch.arange(3)
b = torch.arange(3, 7)

c = torch.einsum('i,j->ij', [a,b])
d = torch.einsum('i,j', [a, b])
e = torch.outer(a, b)

print(c)
print(d)
print(e)

tensor([[ 0,  0,  0,  0],
        [ 3,  4,  5,  6],
        [ 6,  8, 10, 12]])
tensor([[ 0,  0,  0,  0],
        [ 3,  4,  5,  6],
        [ 6,  8, 10, 12]])
tensor([[ 0,  0,  0,  0],
        [ 3,  4,  5,  6],
        [ 6,  8, 10, 12]])


In [ ]:
# 12
a = torch.randn(2, 3, 5)
b = torch.randn(2, 5, 4)

c = torch.einsum('ijk,ikl -> ijl', [a, b])
d = torch.bmm(a, b)

print((c==d).all())

tensor(True)


In [ ]:
# 13
a = torch.randn(2, 3, 5, 7)
b = torch.randn(11, 13, 3, 17, 5)

c = torch.einsum('pqrs,tuqvr -> pstuv', [a, b])
d = torch.tensordot(a, b, dims=([1, 2], [2, 4]))

print((c==d).all())

tensor(True)


In [ ]:
# 14
a = torch.randn(2, 3)
b = torch.randn(5, 3, 7)
c = torch.randn(2, 7)

d = torch.einsum('ik, jkl, il -> ij', [a, b, c])
_m = torch.nn.Bilinear(3, 7, 5, bias=False)
_m.weight.data = b
e = _m(a, c).detach()

print(d.shape)
print((d==e).all())

torch.Size([2, 5])
tensor(True)


In [1]:
# EinOPS